// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provider} from '../models';
import {app} from '../models';
import {main} from '../models';
import {theme} from '../models';
import {config} from '../models';

export function Detail(arg1:string):Promise<provider.Thread>;

export function Diagnose():Promise<app.Diagnostics>;

export function Execute(arg1:main.Request):Promise<main.Result>;

export function ExportTheme(arg1:theme.Palette):Promise<string>;

export function Load():Promise<main.View>;

export function MergeOptions(arg1:string):Promise<provider.MergeOptions>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenItem(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function PickTheme():Promise<string>;

export function Refresh():Promise<main.View>;

export function SaveSettings(arg1:config.Config):Promise<main.View>;

export function Settings():Promise<config.Config>;

export function Theme():Promise<theme.Palette>;
