// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Detail(arg1) {
  return window['go']['main']['Bridge']['Detail'](arg1);
}

export function Diagnose() {
  return window['go']['main']['Bridge']['Diagnose']();
}

export function Execute(arg1) {
  return window['go']['main']['Bridge']['Execute'](arg1);
}

export function ExportTheme(arg1) {
  return window['go']['main']['Bridge']['ExportTheme'](arg1);
}

export function Load() {
  return window['go']['main']['Bridge']['Load']();
}

export function MergeOptions(arg1) {
  return window['go']['main']['Bridge']['MergeOptions'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['Bridge']['OpenFolder'](arg1);
}

export function OpenItem(arg1) {
  return window['go']['main']['Bridge']['OpenItem'](arg1);
}

export function PickFolder() {
  return window['go']['main']['Bridge']['PickFolder']();
}

export function PickTheme() {
  return window['go']['main']['Bridge']['PickTheme']();
}

export function Refresh() {
  return window['go']['main']['Bridge']['Refresh']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['Bridge']['SaveSettings'](arg1);
}

export function Settings() {
  return window['go']['main']['Bridge']['Settings']();
}

export function Theme() {
  return window['go']['main']['Bridge']['Theme']();
}
